SELECT
	// 3. the best basket
	T2.SUPPLIER_ID,
	T2.OFFER_ID,
	GROUP_CONCAT( T2.PART_ID ) AS PART_ID,
	U.`NAME` 
FROM
	(
	SELECT
		// 2. minimum price parts of which
		T.*,
		OD2.ORDER_ID 
	FROM
		(
			// 1 offers for all parts 
			SELECT
			OD.ID AS PART_ID,
			O.SUPPLIER_ID,
			O.OFFER_ID,
			OD.PRICE 
		FROM
			ORDER_DETAIL OD
			INNER JOIN ORDERS O ON O.ID = OD.ORDER_ID 
		WHERE
			O.OFFER_ID = '".$OFFER_ID."' 
			AND OD.`STATUS` = 1 
			AND O.DATEOFORDER IS NOT NULL 
		GROUP BY
			OD.ID 
		ORDER BY
			MIN( OD.PRICE ) 
		) AS T
		INNER JOIN ORDER_DETAIL OD2 ON T.PART_ID = OD2.ID 
	GROUP BY
		OD2.PART_ID 	
	ORDER BY
		MIN( OD2.PRICE ) 
	) AS T2
	INNER JOIN ORDERS O2 ON O2.ID = T2.ORDER_ID
	INNER JOIN USERS U ON U.ID = O2.SUPPLIER_ID 
GROUP BY
	O2.SUPPLIER_ID
